name: Dev Deploy

on:
  push:
    branches:
      - dev

env:
  ENV: development

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, backend1, backend2]

    steps:
      - uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Tag Docker Image
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:dev-${SHORT_SHA} ./${{ matrix.service }}

      - name: Push Docker Image
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:dev-${SHORT_SHA}
