name: Release Backend1

on:
  push:
    paths:
      - 'backend1/**'
    branches:
      - dev

jobs:
  release:
    runs-on: [backend]

    defaults:
      run:
        working-directory: backend1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
